apiVersion: v1
kind: Service
metadata:
  name: python-hello-world
  namespace: default
  labels:
    app: python-hello-world
spec:
  type: LoadBalancer
  selector:
    app: python-hello-world
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None

